services:
  postgres:
    image: postgres:15-alpine
    container_name: finifications-db
    restart: always
    env_file:
      - ./.env
    # No need to expose Postgres externally unless necessary
    # ports:
    #   - "5433:5432"
    volumes:
      - pgdata_finifications:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: finifications-server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: sh -c "./wait-for-it.sh postgres:5432 -- npx prisma migrate deploy && npm start"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: finifications-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  pgdata_finifications:
